language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2.1-003177

cache:
  directories:
    - $HOME/.nuget

script:
  - dotnet restore
  - dotnet build src/Peachpie.PDO.Test.App --configuration Debug --version-suffix dev --build-profile
